package com.jaspercloud.mybatis.support.jdbc;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;

public class ProxyConnection extends AbstractUnsupportedOperationConnection {

    private static ThreadLocal<Boolean> masterTransaction = new InheritableThreadLocal<>();
    private Connection master;
    private Connection slave;

    public static void setMasterTransaction(boolean status) {
        masterTransaction.set(status);
    }

    public ProxyConnection(Connection master, Connection slave) {
        this.master = master;
        this.slave = slave;
    }

    private Connection selectConnection() {
        if (Objects.equals(true, masterTransaction.get())) {
            return master;
        }
        if (RouteDataSource.isSlave() && null != slave) {
            return slave;
        }
        return master;
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        master.setAutoCommit(autoCommit);
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        return master.getAutoCommit();
    }

    @Override
    public void commit() throws SQLException {
        master.commit();
    }

    @Override
    public void rollback() throws SQLException {
        master.rollback();
    }

    @Override
    public void close() throws SQLException {
        master.close();
        if (null != slave) {
            slave.close();
        }
        masterTransaction.remove();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return master.isClosed();
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        master.setReadOnly(readOnly);
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        return master.isReadOnly();
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        master.setTransactionIsolation(level);
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        return master.getTransactionIsolation();
    }

    @Override
    public Statement createStatement() throws SQLException {
        return selectConnection().createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return selectConnection().prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        return selectConnection().prepareCall(sql);
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        return selectConnection().nativeSQL(sql);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return selectConnection().createStatement(resultSetType, resultSetConcurrency);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return selectConnection().prepareStatement(sql, resultSetType, resultSetConcurrency);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return selectConnection().prepareCall(sql, resultSetType, resultSetConcurrency);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return selectConnection().createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return selectConnection().prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return selectConnection().prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return selectConnection().prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return selectConnection().prepareStatement(sql, columnIndexes);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return selectConnection().prepareStatement(sql, columnNames);
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        return selectConnection().getMetaData();
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        master.setHoldability(holdability);
    }

    @Override
    public int getHoldability() throws SQLException {
        return master.getHoldability();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return master.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return master.isWrapperFor(iface);
    }
}
